development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: sample_app
  password: password

test: &test
  adapter: postgresql
  encoding: unicode
  database: db/test
  pool: 5
  username: sample_app
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: db/production
  pool: 5
  username: sample_app
  password: password

cucumber:
  <<: *test